version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mouseTracker
      MYSQL_USER: root
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./backend/sql/db_script.sql:/docker-entrypoint-initdb.d/db_script.sql
    ports:
      - "4036:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "7379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_HOSTNAME: mariadb
      DATABASE_PORT: 3306
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mouseTracker
      DATABASE_USERNAME: root
    depends_on:
#      mariadb:
#        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

volumes:
  mariadb-data:
  redis_data:
